import type { Metadata } from "next";
import { Lexend } from "next/font/google";

import GlobalStyle from "@/styles/global";

const inter = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <GlobalStyle />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
