export const projects = [
  {
    id: "1",
    title: "Woolshoes",
    url: "https://woolshoes.vercel.app/",
    github: "https://github.com/MFelipeSilva/Woolshoes",
    imageUrl: "https://i.ibb.co/FDfR8LN/woolshoes-ecommerce.gif",
    technologies: ["Nextjs", "Typescript", "Node.js"],
  },
  {
    id: "2",
    title: "Clone Tesla",
    url: "https://clonedtesla.vercel.app/",
    github: "https://github.com/MFelipeSilva/clone-tesla",
    imageUrl: "https://i.ibb.co/jJdsJr7/clone-tesla.gif",
    technologies: ["React", "Styled Components", "Context API"],
  },
  {
    id: "3",
    title: "Weather Forecast",
    url: "https://weather-forecast-murex.vercel.app/",
    github: "https://github.com/MFelipeSilva/weather-forecast",
    imageUrl: "https://i.ibb.co/cDNPq0z/weather-forecast.gif",
    technologies: ["Nextjs", "Redux", "Tailwind"],
  },
  {
    id: "4",
    title: "Personspace",
    url: "https://personspace-web.vercel.app/",
    github: "https://github.com/RichardPompeo/personspace",
    imageUrl: "https://i.ibb.co/n06q8Jg/personpace.gif",
    technologies: ["Nextjs", "Typescript", "GraphQL"],
  },
  {
    id: "5",
    title: "Search Github",
    url: "https://search-github-mu.vercel.app/",
    github: "https://github.com/MFelipeSilva/search-github",
    imageUrl: "https://i.ibb.co/jRjLBhx/search-github.gif",
    technologies: ["React", "Styled Components", "Redux"],
  },

  {
    id: "6",
    title: "Let's Travel",
    url: "https://lets-travel-two.vercel.app/",
    github: "https://github.com/MFelipeSilva/lets-travel",
    imageUrl: "https://i.ibb.co/2Z1YwFK/let-s-travel.gif",
    technologies: ["React", "Styled Components", "Context API"],
  },
];
